### ISSUE TITLE
New Problems a Rise 

### ISSUE THREAD

**Issue by XavierDD1st** [jOOQ/jOOR#59]
### Expected behavior and actual behavior:
To run. 
```"C:\Program Files\Java\jdk1.8.0_172\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5\lib\idea_rt.jar=58316:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_172\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\rt.jar;C:\Project\TBUA\out\production\classes;C:\Users\2.0\.gradle\caches\modules-2\files-2.1\org.jooq\joor-java-8\0.9.9\527dbfbab7baf8a6d8ea95c991a8309e456eb9af\joor-java-8-0.9.9.jar;C:\Users\2.0\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.6\815893df5f31da2ece4040fe0a12fd44b577afaf\commons-io-2.6.jar;C:\Users\2.0\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.5\f645ed69d595b24d4cf8b3fbb64cc505bede8829\gson-2.8.5.jar" io.github.xavierdd1st.Main
file: C:\Project\TBUA\plugins\null.json
{"provider":"HappyPlugin","name":"TimeViewer","commandName":"time","info":"Shows the time","code":["package io.github.xavierdd1st.commands;","import java.time.Clock;","import java.time.ZoneId;","public class TimeViewer extends Command {","public void command() {","Clock clock \u003d Clock.system(ZoneId.systemDefault());","CommandParser.setOutput( clock.toString() );","}","}"]}
Exception in thread "main" org.joor.ReflectException: java.lang.reflect.InvocationTargetException
	at org.joor.Reflect.on(Reflect.java:781)
	at org.joor.Reflect.call(Reflect.java:463)
	at org.joor.Compile.compile(Compile.java:73)
	at org.joor.Reflect.compile(Reflect.java:77)
	at io.github.xavierdd1st.commands.CommandParser.parseCode(CommandParser.java:22)
	at io.github.xavierdd1st.commands.CommandHandler.setup(CommandHandler.java:16)
	at io.github.xavierdd1st.Main.<init>(Main.java:21)
	at io.github.xavierdd1st.Main.main(Main.java:35)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.joor.Reflect.on(Reflect.java:777)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: io/github/xavierdd1st/TimeViewer (wrong name: io/github/xavierdd1st/commands/TimeViewer)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	... 12 more
```
### Steps to reproduce the problem:
Same steps
https://github.com/XavierDD1st/TBUA
### Versions:

- jOOR: 0.9.9
- Java: 8

**Comment by XavierDD1st** [comment]
Not related to the Issue, but this is an amazing project.

**Comment by lukaseder** [comment]
Thanks for your report. The problem is literally described by the exception. You're trying to load `io/github/xavierdd1st/TimeViewer`, when the class is really located in `io/github/xavierdd1st/commands/TimeViewer`

Cheers
