### ISSUE TITLE
Cannot compile nested or additional top-level classes

### ISSUE THREAD

**Issue by lburgazzoli** [jOOQ/jOOR#71]
### Expected behavior and actual behavior:

I have this class that is loaded and compiled through jOOR:

```java
package com.example;

import org.apache.camel.Exchange;
import org.apache.camel.Processor;
import org.apache.camel.builder.RouteBuilder;

public class WithCustomProcessor extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        Processor ucp = new Processor() {
            public void process(Exchange exchange) throws Exception {
                String body = exchange.getIn().getBody(String.class);
                body = body.toUpperCase();
                exchange.getOut().setBody(body);
            }
        };

        from("timer:tick?period=10s")
              .setBody().constant("Hello")
            .process(ucp)
            .to("log:info");
    }
}
```

But when the the method `configure` is invoked from the compiled object, the following exception is thrown:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/example/WithCustomProcessor$1
	at com.example.WithCustomProcessor.configure(WithCustomProcessor.java:13)
	at com.github.lburgazzoli.JoorTest.main(JoorTest.java:15)
Caused by: java.lang.ClassNotFoundException: com.example.WithCustomProcessor$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

### Steps to reproduce the problem:

I have a repo with a reproducer [here](https://github.com/lburgazzoli/camel-joor-test). 
Running the main class will reproduce the issue.

### Versions:

- jOOR: 0.9.9
- Java: openjdk version "1.8.0_191"

**Comment by lukaseder** [comment]
Thanks a lot for your report. Interesting observation. Of course, an individual compilation unit (Java source code unit) can produce more than one class. Not just when nesting classes, but also at the top level. We should definitely make sure those classes are loaded as well.

Will need to think about how this is fixable.

**Comment by lukaseder** [comment]
The workaround in your case is to use a lambda, I suspect? This should work:

```java
package com.example;

import org.apache.camel.Exchange;
import org.apache.camel.Processor;
import org.apache.camel.builder.RouteBuilder;

public class WithCustomProcessor extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        Processor ucp = exchange -> {
            String body = exchange.getIn().getBody(String.class);
            body = body.toUpperCase();
            exchange.getOut().setBody(body);
        };

        from("timer:tick?period=10s")
              .setBody().constant("Hello")
            .process(ucp)
            .to("log:info");
    }
}
```

**Comment by lburgazzoli** [comment]
Yes lambda do work

**Comment by lukaseder** [comment]
This was actually not that hard to fix. The compiler sends several compiled classes, we're just ignoring all of them, except for the top level class.
